ImgVisionApp.constant('urlConstants', {
    myWorkItemBasket: "https://nextgendigitalimagingapitest.corp.pep.pvt/api/UserSecurity/GetMyWorkitems/",
    adminTreeGetWorkflows:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/UserSecurity/GetUserWorkflows/",
    adminTreeGetWorkQueues:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/Workflow/GetWorkFlowQueueStats/",
    adminTreeGetWorkItems:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/Workflow/GetWorkItems/",
    routingActions:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/WorkflowManager/MoveWorkItem/",
    GetBusinessAreas:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/UserSecurity/GetUserBusinessAreas/",
    GetDocumentTypes:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/UserSecurity/GetUserDocumentTypes/",
    GetIndexingFields:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/StorageObject/CopyDocumentTypeInfo/",
    GetDocumentTypeInfo:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/StorageObject/GetDocumentTypeInfo/",
    workItemBasketViewHistoryByWKID:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/WorkflowManager/GetWorkItemHistoryByWkID/",
    workItemBasketViewHistoryByFNID:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/WorkflowManager/GetWorkItemHistoryByFNID/",
    workItemBasketViewNotesByWKID:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/WorkflowManager/GetWorkItemNotesByWkID/",
    workItemBasketViewNotesByFNID:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/WorkflowManager/GetWorkItemNotesByFNID/",
    addNotes:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/WorkflowManager/AddWorkItemNote/",
    uploadFile:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/StorageObject/UpdateDocument/",
    getDocumentTypes:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/StorageObject/GetDocumentTypes/",
    updateDocumentType:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/Admin/UpdateDocumentType/",
    activateWorkItem:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/Workflow/UpdateWorkitemStatus",
    deleteWorkItem:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/Workflow/DeleteWorkItems",
    reAssignWorkItem:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/Workflow/AssignOrReleaseWorkItems",
    workItemIndexingFields:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/StorageObject/GetIndexingFieldsWithValues/",
    link:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/StorageObject/GetDocumentLink/",
    email:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/StorageObject/GetDocumentLinkEmailInfo/",
    sendEmail:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/StorageObject/EmailDocumentLink",
    viewWorkFlowHistory:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/Workflow/GetWorkflowHistoryByDocID/",
    addDocumentNotes:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/StorageObject/AddDocumentNote/",
    viewDocumentNotes:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/StorageObject/GetDocumentNotesByDocID/",
    viewWorkFlowNotes:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/Workflow/GetWorkItemNotesByDocID/",
    reAssignItemGpIds:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/UserSecurity/GetUsers/",
    alterItemGpIds:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/UserSecurity/GetUserDocumentTypes",
    alterWorkItem:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/WorkflowManager/AlterDocumentType",
    retrievalSearchField: "https://nextgendigitalimagingapitest.corp.pep.pvt/api/StorageObject/GetSearchFields/",
    retrievalSearchResults: "https://nextgendigitalimagingapitest.corp.pep.pvt/api/StorageObject/SearchDocuments/",
    getDocumentProperties: "https://nextgendigitalimagingapitest.corp.pep.pvt/api/StorageObject/GetDocumentProperties/",
    getUserPreferences: "https://nextgendigitalimagingapitest.corp.pep.pvt/api/UserSecurity/GetUserSystemPreference/",
    saveUserPreferences: "https://nextgendigitalimagingapitest.corp.pep.pvt/api/UserSecurity/SaveUserPreference",
    createDocument:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/StorageObject/CreateDocument/",
    getFileSize:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/StorageObject/GetUploadFileSizeLimit/",
    addPages:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/StorageObject/AddPages/",
    exportExcel:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/StorageObject/ExportSearchResult",
    logOut:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/UserSecurity/SignOut",
    downloadWorkItem:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/WorkflowManager/GetDownloadURL/",
    saveIndexingFields:"https://nextgendigitalimagingapitest.corp.pep.pvt/api/StorageObject/SaveIndexingFields/"
});